name: kvmtool build

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      RELEASES_REPO_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

env:
  CI_REPO: https://github.com/opencca/ci-scripts
  CI_RUN_SCRIPT: run-ci.sh
  CI_BUILD_SCRIPT: build-kvmtool.sh
  upload-snapshot: false

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.branch }}
          submodules: recursive
          clean: true
          path: kvmtool
        

      - name: Run build script
        run: |
          rm -rf .ci || true
          git clone --depth 1 "$CI_REPO" .ci
          cd .ci
          ./"$CI_RUN_SCRIPT" "$GITHUB_WORKSPACE" ./"$CI_BUILD_SCRIPT"
    
      - name: Upload snapshot
        if: ${{ env.upload-snapshot }}
        uses: actions/upload-artifact@v4
        with:
          name: kvmtool-snapshot
          path: snapshot/lkvm
          if-no-files-found: error