
name: release-debian-rootfs

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: opencca/main
      clean:
        type: boolean
        default: false
      dry-run:
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true

env:
  CI_REPO: https://github.com/opencca/ci-scripts
  CI_RUN_SCRIPT: run-ci.sh
  CI_BUILD_SCRIPT: build-debos-rootfs.sh

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: opencca/debian-image-recipes
          ref: ${{ inputs.branch }}
          submodules: recursive
          clean:  ${{ inputs.clean }}
          path: debian-image-recipes
      
      - name: Checkout assets
        uses: actions/checkout@v4
        with:
          repository: opencca/opencca-assets
          ref: opencca/main
          clean:  false
          path: opencca-assets

      - name: Run build script
        run: |
          rm -rf .ci || true
          git clone --depth 1 "$CI_REPO" .ci
          cd .ci
          ./"$CI_RUN_SCRIPT" "$GITHUB_WORKSPACE" ./"$CI_BUILD_SCRIPT"
          
      - name: Mark commit hashes
        uses: opencca/ci-scripts/.github/actions/commit-hash@opencca/main
        with:
          repos: |
            ./debian-image-recipes debian-image-recipes
          output: snapshot/commits.txt

      - name: Upload snapshot release
        if: ${{ !inputs.dry-run }}
        uses: opencca/ci-scripts/.github/actions/release@opencca/main
        with:
          project: rootfs
          branch: ${{ inputs.branch }}
          artifact: |
            snapshot/commits.txt
            debian-image-recipes/out/opencca-image-rockchip-rock5b-rk3588.bmap
            debian-image-recipes/out/opencca-image-rockchip-rock5b-rk3588.img.gz
            opencca-assets/rk3588/rk3588_spl_loader_v1.08.111.bin
          token: ${{ secrets.RELEASES_REPO_TOKEN }}